### ISSUE TITLE
Promo Images, Final

### ISSUE THREAD

**Issue by bam32099** [IDM-SP-2021/afiye#63]
Promo Images, Two (2) Images minimum

The promo images should not have logos or text on them - no overlays
Great art gets great press coverage - seek to create compelling images that demand attention
Minimum resolution should be approximately 1920x1080 at this stage but you may want to increase resolution in later drafts
provide a high quality, minimum compression jpg or a png (especially if you have an image that benefits from an alpha channel)

**Comment by bb837** [comment]
Ok so I finished the illustrations today, as they are on the drive. I also have a folder called 'media gallery' on the drive that is the all the promotional stuff we will provide in a zip.

Is this what you want? If there is anything you think of that you want to be added please let me know. Otherwise I will close this issue

**Comment by bb837** [comment]
I will leave this up/ open until it is due so that any record for changes is documented
